### ISSUE TITLE
App Crashing in Offline Mode

### ISSUE THREAD

**Issue by akshatbhuhagal** [shruddms/OfflineCachingSample#1]
Initial time App storing all the data inside our Local Storage (RoomDB) but when we try to run our application without internet then it's crashing because it's not able to understand whether our app has internet connection or not (offline)

Please check given screen recording for reference : 

https://github.com/shruddms/OfflineCachingSample/assets/50077510/736ab61e-aaf2-4dc7-84af-9036c0544e57

**Comment by orioonyx** [comment]
The issue has been resolved with the merged [PR](https://github.com/shruddms/OfflineCachingSample/pull/2). The app crash in offline mode has been fixed. Thank you, @akshatbhuhagal , for your contribution!
